# Retail Pricing & Promotion Optimization
#
# The eight pipeline steps are strictly ordered and each reads the previous
# step's output. Running them by hand in the wrong order trips the
# `check_pipeline_dependencies` guard; this encodes the order instead.

PYTHON ?= python
# Keep any caller-supplied dependency path while making repository imports
# deterministic. Overwriting PYTHONPATH breaks isolated or vendored runtimes.
export PYTHONPATH := $(CURDIR):$(PYTHONPATH)

STEPS := \
	step_01_data_validation \
	step_02_exploratory_analysis \
	step_03_price_elasticity \
	step_04_iv_causal_model \
	step_05_promotion_uplift \
	step_06_demand_forecasting \
	step_07_rag_features \
	step_08_price_optimization

.PHONY: help install pipeline test test-python test-js parity demo-data validate release-status clean $(STEPS)

help:
	@echo "make install         - install Python dependencies"
	@echo "make pipeline        - run all eight steps in order"
	@echo "make test            - run the Python test suite"
	@echo "make test-python     - alias for the Python test suite"
	@echo "make test-js         - run the ELASTIQ engine + parity tests"
	@echo "make parity          - regenerate the cross-language parity fixture"
	@echo "make demo-data       - regenerate the frontend demo data from the pipeline"
	@echo "make validate        - pipeline, then both test suites"
	@echo "make release-status  - regenerate FINAL_RELEASE.md's validation table"
	@echo "make clean           - remove derived data and models"

install:
	$(PYTHON) -m pip install -r requirements.txt

pipeline: $(STEPS)

$(STEPS):
	@echo "=== $@ ==="
	$(PYTHON) -m src.pipelines.$@

test:
	$(PYTHON) -m pytest

test-python: test

parity:
	$(PYTHON) scripts/generate_parity_fixture.py

demo-data:
	$(PYTHON) scripts/export_demo_data.py

test-js:
	cd app/frontend && npm ci && npm test

# The parity fixture is generated by the Python engine and consumed by the
# JavaScript one, so it must be refreshed before the JS suite runs.
validate: pipeline parity demo-data test test-js

release-status:
	$(PYTHON) scripts/generate_release_status.py

clean:
	rm -rf data/interim data/processed
	rm -f models/*.pkl models/*.joblib models/*.npy
