import { fmtMoney, fmtPrice, fmtPct, fmtPctPlain, fmtNum, ACTION_LABEL } from "../../lib/format.js";
import Icon from "../Icon.jsx";

export default function ReportView({ result, cfg, techName, onPdf, onCsv }) {
  const now = new Date();
  const top = [...result.rows].sort((a,b)=>b.profitChange-a.profitChange).slice(0,6);
  const all = result.validation.find(v=>v.check==="All checks passed");
  const bindings = {step:result.rows.filter(r=>r.stepBinding).length, competitor:result.rows.filter(r=>r.competitorBinding).length, inventory:result.rows.filter(r=>r.inventoryBinding).length};
  return <div className="stack">
    <section className="panel"><div className="panel-head"><div><span className="section-kicker">Stakeholder deliverable</span><h3>Executive decision report</h3><p className="panel-sub">A concise, auditable summary of the recommendation, financial impact, controls and assumptions.</p></div><div className="btn-group"><button className="btn ghost" onClick={onCsv}>Download CSV</button><button className="btn ghost" onClick={()=>window.print()}>Print view</button><button className="btn" onClick={onPdf}><Icon name="download" size={16}/> Download PDF</button></div></div>
      <div className="report" id="report-body">
        <div className="rpt-header"><div><div className="rpt-title">ELASTIQ Pricing Decision Report</div><div className="rpt-sub">{techName} · {now.toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"})}</div></div><div className="rpt-badge">DECISION SUPPORT</div></div>
        <div className="report-callout"><span>Executive recommendation</span><h2>Capture {fmtMoney(result.exec.totalProfitChange)} in expected profit uplift with {fmtPctPlain(all.passRate)} control readiness.</h2><p>Across {result.exec.totalItems} decision units, the plan proposes {result.exec.increase} increases, {result.exec.decrease} decreases and {result.exec.hold} holds. Expected revenue changes by {fmtPct(result.exec.revenueChangeRate)} and expected profit by {fmtPct(result.exec.profitChangeRate)} versus current pricing.</p></div>
        <div className="rpt-kpis"><div><span>Expected profit</span><b>{fmtMoney(result.exec.totalExpectedProfit)}</b><small>{fmtPct(result.exec.profitChangeRate)} vs current</small></div><div><span>Expected revenue</span><b>{fmtMoney(result.exec.totalExpectedRevenue)}</b><small>{fmtPct(result.exec.revenueChangeRate)} vs current</small></div><div><span>Average move</span><b>{fmtPct(result.exec.avgPriceChangeRate)}</b><small>{result.exec.increase} up · {result.exec.decrease} down</small></div><div><span>Control readiness</span><b>{fmtPctPlain(all.passRate)}</b><small>{all.passed}/{all.total} units pass</small></div></div>
        <h4 className="rpt-h">Priority action queue</h4>
        <table className="tbl compact"><thead><tr><th>Priority</th><th>Unit</th><th>Category</th><th className="r">Current</th><th className="r">Recommended</th><th>Action</th><th className="r">Profit impact</th></tr></thead><tbody>{top.map((r,i)=><tr key={r.itemId}><td>{i+1}</td><td className="mono strong">{r.itemId}</td><td>{r.category}</td><td className="r mono">{fmtPrice(r.currentPrice)}</td><td className="r mono">{fmtPrice(r.recommendedPrice)}</td><td>{ACTION_LABEL[r.recommendationAction]}</td><td className="r mono">{fmtMoney(r.profitChange)}</td></tr>)}</tbody></table>
        <div className="report-two-col"><div><h4 className="rpt-h">Control summary</h4><table className="tbl compact"><tbody><tr><td>All checks passed</td><td className="r mono">{all.passed}/{all.total}</td></tr><tr><td>Step capped</td><td className="r mono">{bindings.step}</td></tr><tr><td>Competitor capped</td><td className="r mono">{bindings.competitor}</td></tr><tr><td>Inventory bound</td><td className="r mono">{bindings.inventory}</td></tr><tr><td>Promotions proposed</td><td className="r mono">{result.exec.promoRecommended}</td></tr></tbody></table></div><div><h4 className="rpt-h">Action distribution</h4><table className="tbl compact"><tbody><tr><td>Increase</td><td className="r mono">{result.exec.increase}</td></tr><tr><td>Decrease</td><td className="r mono">{result.exec.decrease}</td></tr><tr><td>Hold</td><td className="r mono">{result.exec.hold}</td></tr><tr><td>Review</td><td className="r mono">{result.exec.review}</td></tr><tr><td>Total decisions</td><td className="r mono">{result.exec.totalItems}</td></tr></tbody></table></div></div>
        <h4 className="rpt-h">Scenario comparison</h4><table className="tbl compact"><thead><tr><th>Strategy</th><th className="r">Demand</th><th className="r">Revenue</th><th className="r">Profit</th><th className="r">Δ Revenue</th><th className="r">Δ Profit</th></tr></thead><tbody>{result.portfolio.map(p=><tr key={p.key} className={p.key==="recommended"?"row-rec":""}><td>{p.name}</td><td className="r mono">{fmtNum(p.demand)}</td><td className="r mono">{fmtMoney(p.revenue)}</td><td className="r mono">{fmtMoney(p.profit)}</td><td className="r mono">{fmtPct(p.revenueChangeRate)}</td><td className="r mono">{fmtPct(p.profitChangeRate)}</td></tr>)}</tbody></table>
        <h4 className="rpt-h">Category contribution</h4><table className="tbl compact"><thead><tr><th>Category</th><th className="r">Units</th><th className="r">Avg move</th><th className="r">Revenue impact</th><th className="r">Profit impact</th></tr></thead><tbody>{result.categories.map(c=><tr key={c.category}><td>{c.category}</td><td className="r mono">{c.items}</td><td className="r mono">{fmtPct(c.avgPriceChangeRate)}</td><td className="r mono">{fmtMoney(c.revenueChange)}</td><td className="r mono">{fmtMoney(c.profitChange)}</td></tr>)}</tbody></table>
        <h4 className="rpt-h">Run assumptions and guardrails</h4><div className="rpt-assumptions"><div><span>Method</span><b>{techName}</b></div><div><span>Objective</span><b>{cfg.objective}</b></div><div><span>Minimum margin</span><b>{fmtPctPlain(cfg.minMarginRate)}</b></div><div><span>Implementation step</span><b>{fmtPctPlain(cfg.maxImplementationStep)}</b></div><div><span>Maximum increase</span><b>{fmtPctPlain(cfg.maxPriceChangeRate)}</b></div><div><span>Maximum decrease</span><b>{fmtPctPlain(-cfg.minPriceChangeRate)}</b></div><div><span>Competitor tolerance</span><b>±{fmtPctPlain(cfg.competitorPriceTolerance)}</b></div><div><span>Promotion threshold</span><b>{fmtPctPlain(cfg.promotionUpliftThreshold)}</b></div></div>
        <p className="rpt-foot">Demand model: constant elasticity q(P)=q0·(P/P0)^ε. Profit=(P−cost)·q less promotion cost. Recommendations are bounded by margin, competitor, inventory and implementation-step controls. They are decision support outputs and require commercial review before execution.</p>
      </div>
    </section>
  </div>;
}
