import { fmtPrice, fmtPctPlain } from "../../lib/format.js";

export default function ValidationView({ result }) {
  const all=result.validation.find(v=>v.check==="All checks passed");
  const bindings={inventory:result.rows.filter(r=>r.inventoryBinding).length,competitor:result.rows.filter(r=>r.competitorBinding).length,step:result.rows.filter(r=>r.stepBinding).length};
  return <div className="stack">
    <section className={`control-hero ${all.passRate===1?"ready":"attention"}`}><div><span className="hero-label">Control decision</span><h2>{all.passRate===1?"The current plan passes every configured commercial control.":`${all.failed} recommendations require attention before approval.`}</h2><p>Binding constraints show where policy actively shapes a recommendation; they are not violations.</p></div><div className="control-score"><strong>{fmtPctPlain(all.passRate)}</strong><span>overall pass rate</span></div></section>
    <div className="metric-grid three"><article className="metric-card"><span>Implementation step capped</span><strong>{bindings.step}</strong><small>recommendations pulled toward current price</small></article><article className="metric-card"><span>Competitor capped</span><strong>{bindings.competitor}</strong><small>recommendations bounded by market range</small></article><article className="metric-card"><span>Inventory bound</span><strong>{bindings.inventory}</strong><small>demand limited by available stock</small></article></div>
    <section className="panel"><div className="panel-head"><div><span className="section-kicker">Policy checks</span><h3>Pass rate by control</h3><p className="panel-sub">Every recommendation is tested independently against the complete policy set.</p></div></div><div className="validation-list">{result.validation.map(v=><div className={`validation-row ${v.check==="All checks passed"?"total":""}`} key={v.check}><div><b>{v.check}</b><small>{v.failed?`${v.failed} failed`:"No exceptions"}</small></div><div className="validation-bar"><i className={v.passRate===1?"ok":"warn"} style={{width:`${v.passRate*100}%`}}/></div><strong>{v.passed}/{v.total}</strong><span>{fmtPctPlain(v.passRate)}</span></div>)}</div></section>
    <section className="panel"><div className="panel-head"><div><span className="section-kicker">Constraint map</span><h3>Binding controls by decision unit</h3><p className="panel-sub">Review units whose model optimum was adjusted by one or more guardrails.</p></div></div><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Unit</th><th>Category</th><th className="r">Recommended</th><th className="r">Margin</th><th className="c">Inventory</th><th className="c">Competitor</th><th className="c">Step</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.itemId}><td className="mono strong">{r.itemId}</td><td>{r.category}</td><td className="r mono">{fmtPrice(r.recommendedPrice)}</td><td className="r mono">{fmtPctPlain(r.optimizedMarginRate)}</td><td className="c"><span className={`control-pill ${r.inventoryBinding?"binding":"ok"}`}>{r.inventoryBinding?"Binding":"Clear"}</span></td><td className="c"><span className={`control-pill ${r.competitorBinding?"binding":"ok"}`}>{r.competitorBinding?"Capped":"Clear"}</span></td><td className="c"><span className={`control-pill ${r.stepBinding?"binding":"ok"}`}>{r.stepBinding?"Capped":"Clear"}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
