"""
Regenerate the frontend's demo seed data from real pipeline output.

app/frontend/src/lib/demoData.js feeds the ELASTIQ demo app's client-side
optimizer (app/frontend/src/lib/engine.js). The demo is a static site with
no backend, so "real data" here means: aggregate the actual, freshly
computed data/processed/price_optimization_recommendations.csv (plus its
elasticity and RAG-signal sources) down to one row per product and write
it out as a JS module, instead of hand-typed or stale numbers.

Run after `python -m src.pipelines.step_08_price_optimization` (and its
upstream steps) to keep the demo in sync with the real model.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.config import PROCESSED_DIR, PROJECT_ROOT
from src.optimization import build_product_summary

OUTPUT_FILE = (
    PROJECT_ROOT / "app" / "frontend" / "src" / "lib" / "demoData.js"
)

def _load_inputs() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    recommendations = pd.read_csv(
        PROCESSED_DIR / "price_optimization_recommendations.csv"
    )
    elasticity_estimates = pd.read_csv(
        PROCESSED_DIR / "product_elasticity_estimates.csv"
    )
    rag_features = pd.read_csv(
        PROCESSED_DIR / "retail_with_rag_features.csv"
    )
    return recommendations, elasticity_estimates, rag_features


def _format_js_row(row: pd.Series) -> str:
    fields = [
        f'itemId: "{row.itemId}"',
        f'productId: "{row.productId}"',
        f'category: "{row.category}"',
        f"currentPrice: {row.currentPrice}",
        f"unitCost: {row.unitCost}",
        f"competitorPrice: {row.competitorPrice}",
        f"inventory: {row.inventory}",
        f"baselineQuantity: {row.baselineQuantity}",
        f"elasticity: {row.elasticity}",
        f'elasticitySource: "{row.elasticitySource}"',
        f"elasticityIsCausal: {str(bool(row.elasticityIsCausal)).lower()}",
        f'baselineSource: "{row.baselineSource}"',
        f"promotionUpliftRate: {row.promotionUpliftRate}",
        f"promotionModelReliable: {str(bool(row.promotionModelReliable)).lower()}",
        f"confidence: {row.confidence}",
        f"ragSignal: {row.ragSignal}",
        f"promotionFlag: {row.promotionFlag}",
        f'dataAsOfDate: "{row.dataAsOfDate}"',
    ]
    return "  { " + ", ".join(fields) + " },"


def _write_js_module(products: pd.DataFrame, output_file: Path) -> None:
    rows = "\n".join(
        _format_js_row(row) for _, row in products.iterrows()
    )

    content = (
        "/* ==========================================================================\n"
        "   DEMO DATA — auto-generated by scripts/export_demo_data.py from the real,\n"
        "   freshly computed data/processed/price_optimization_recommendations.csv\n"
        "   (plus product_elasticity_estimates.csv and retail_with_rag_features.csv),\n"
        "   aggregated to one row per product. Do not hand-edit; re-run the export\n"
        "   script after a fresh pipeline run instead.\n"
        "   ========================================================================== */\n"
        "export const DEMO_DATA = [\n"
        f"{rows}\n"
        "];\n"
    )

    output_file.write_text(content, encoding="utf-8")


def main() -> None:
    recommendations, elasticity_estimates, rag_features = _load_inputs()

    products = build_product_summary(
        recommendations, elasticity_estimates, rag_features
    )

    if products.empty:
        raise ValueError(
            "No successful recommendations were found to export. Run "
            "the pipeline (steps 01-08) first."
        )

    _write_js_module(products, OUTPUT_FILE)

    print(f"Exported {len(products)} products to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
